2018-04-16T14:27:33.985Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: The current identity, with the name 'admin' and the identifier '7d195e0cbc77f47d78f39e21ec879210cdff2f8506d5f326af245563ebfcbb69', must be activated (ACTIVATION_REQUIRED))
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T14:27:33.986Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity, with the name 'admin' and the identifier '7d195e0cbc77f47d78f39e21ec879210cdff2f8506d5f326af245563ebfcbb69', must be activated (ACTIVATION_REQUIRED))","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity, with the name 'admin' and the identifier '7d195e0cbc77f47d78f39e21ec879210cdff2f8506d5f326af245563ebfcbb69', must be activated (ACTIVATION_REQUIRED))\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T14:27:33.986Z ERROR   HLFConnection           :ping()                   {"message":"Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity, with the name 'admin' and the identifier '7d195e0cbc77f47d78f39e21ec879210cdff2f8506d5f326af245563ebfcbb69', must be activated (ACTIVATION_REQUIRED))","stack":"Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity, with the name 'admin' and the identifier '7d195e0cbc77f47d78f39e21ec879210cdff2f8506d5f326af245563ebfcbb69', must be activated (ACTIVATION_REQUIRED))\n    at _checkRuntimeVersions.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:713:34)\n    at <anonymous>"}$
2018-04-16T14:32:53.689Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'KYCID001' as the object already exists)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T14:32:53.690Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'KYCID001' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'KYCID001' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-04-16T14:33:04.942Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'KYCID001' as the object already exists)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T14:33:04.942Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'KYCID001' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'KYCID001' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-04-16T14:43:52.165Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'KYCID001' as the object already exists)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T14:43:52.165Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'KYCID001' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'KYCID001' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-04-16T15:34:55.079Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:34:55.079Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:34:56.351Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:34:56.352Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:34:56.620Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:34:56.620Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:34:56.779Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:34:56.779Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:34:57.510Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:34:57.511Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:34:57.581Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:34:57.581Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:34:57.759Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:34:57.760Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:34:57.923Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:34:57.924Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:34:58.227Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:34:58.227Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:34:58.297Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:34:58.298Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:34:58.516Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:34:58.516Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:34:58.690Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:34:58.690Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0002' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:35:03.048Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0003' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:35:03.048Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0003' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0003' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:35:03.745Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0003' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:35:03.745Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0003' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0003' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:35:03.870Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0003' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:35:03.871Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0003' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0003' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:35:04.192Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0003' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:35:04.192Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0003' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0003' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:35:04.295Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0003' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:35:04.296Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0003' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0003' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:35:04.525Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0003' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:35:04.525Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0003' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID0003' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:36:20.656Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:36:20.656Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:36:21.995Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:36:21.995Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:36:22.613Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:36:22.613Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:36:22.844Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:36:22.844Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:36:23.033Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:36:23.033Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:38:12.742Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:38:12.743Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:38:21.075Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:38:21.075Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-04-16T15:38:22.868Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)
    at /home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-16T15:38:22.869Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'KYCID084' in collection with ID 'Asset:org.acme.model.suspiciousAccountAsset' does not exist)\n    at channel.queryByChaincode.then.catch (/home/malak/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
